---
title: "LOUAHLIA"
author: "Sami Louahlia"
format: html

code-fold: true
---

```{r}
here::i_am("stars.Rproj")
library(here)
library(vroom)
library(ggplot2)
library(tidyr)
library(dplyr)
```

[Access to the github repository](https://github.com/SamiLhl/stars)

```{r Q3-1}
Main_Data <- vroom(here("Data folder/DATA-PLANETS.csv"))

```
We load the Main data file, it contains `r nrow(Main_Data)` planets and `r ncol(Main_Data)` variables including vars for planet number and their names. As of now, numerical variables are not all seen as numerical. Need to change that

```{r Q3-2}
Main_Data$`MASS (EARTH)`<-as.numeric(Main_Data$`MASS (EARTH)`)
Main_Data$Density <- as.numeric(Main_Data$Density)

is.numeric(Main_Data$`MASS (EARTH)`)
is.numeric(Main_Data$Density)
```
Now they should be in numerical format. 

```{r Q4}
Row <- nrow(Main_Data)
Col <- ncol(Main_Data)
NA_key <- Main_Data |> count(is.na(STAR_KEY)==TRUE)
NA_number <- Main_Data |> count(is.na(PLANET_NUMBER)== TRUE)
NA_name <- Main_Data |> count(is.na(planet_name)== TRUE)
NA_mass <- Main_Data |> count(is.na(`MASS (EARTH)`)== TRUE)
NA_density <- Main_Data |> count(is.na(Density)== TRUE)
NA_rad <- Main_Data |> count(is.na(`relative radius`)== TRUE) 
NA_ter <- Main_Data |> count(is.na(`type of terrain`)== TRUE)
NA_clim <- Main_Data |> count(is.na(`type of climate`)== TRUE)

TableVariable <- Main_Data |> summarise(Row, Col, NA_key, NA_number, NA_name, NA_mass, NA_density, NA_rad, NA_ter, NA_clim )
Q4 <- knitr:: kable(TableVariable)
```


This table summarizes how many NA's there are in each variable `r Q4`

```{r Q5}
Main_Data_plot <- na.omit(Main_Data)
ggplot(Main_Data_plot, aes(x=`MASS (EARTH)`, y=`relative radius`)) +
  geom_point()+
  ggtitle("Mass of planets as a function of their radius")+
  xlab("Mass of planet in earth mass")+
  ylab("Relative radius")
```

